import { describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import { generateMainSource, scanEventFiles } from '../src/cli/generate';

const FIXTURES_DIR = join(import.meta.dir, 'fixtures');

describe('scanEventFiles', () => {
  test('src/events/直下の.tsファイル名(拡張子抜き)をソート済みで返す', () => {
    const names = scanEventFiles(join(FIXTURES_DIR, 'events'));
    expect(names).toEqual(['messageCreate', 'ready']);
  });

  test('イベントファイルが存在しない場合は空配列', () => {
    const names = scanEventFiles(join(FIXTURES_DIR, 'events-empty'));
    expect(names).toEqual([]);
  });

  test('interactionCreate.tsが存在する場合はthrow', () => {
    expect(() => scanEventFiles(join(FIXTURES_DIR, 'events-reserved'))).toThrow(/interactionCreate/);
  });
});

describe('generateMainSource', () => {
  test('イベントごとに静的importとclient.onバインドを生成する', () => {
    const source = generateMainSource(['ready', 'messageCreate']);
    expect(source).toContain(`import readyHandler from '../src/events/ready';`);
    expect(source).toContain(`import messageCreateHandler from '../src/events/messageCreate';`);
    expect(source).toContain(`client.on('messageCreate', messageCreateHandler);`);
  });

  test('readyイベントだけはEvents.ClientReadyで購読する(実際の値はclientReadyで非推奨のready文字列とは異なるため)', () => {
    const source = generateMainSource(['ready']);
    expect(source).toContain('client.on(Events.ClientReady, readyHandler);');
    expect(source).not.toContain(`client.on('ready', readyHandler);`);
  });

  test('イベントが1つもない場合でも有効なソースを生成する(ぶら下がりimportなし)', () => {
    const source = generateMainSource([]);
    expect(source).not.toContain('Handler');
    expect(source).toContain('async function main()');
  });

  test('componentsは動的importされる', () => {
    const source = generateMainSource([]);
    expect(source).toContain(`await import('../src/components/buttons')`);
    expect(source).toContain(`await import('../src/components/selectMenus')`);
    expect(source).toContain(`await import('../src/components/slashCommands')`);
  });

  test('slashCommandのREST登録は一切含まない(disbord commands pushが唯一の登録手段のため)', () => {
    const source = generateMainSource([]);
    expect(source).not.toContain('REST');
    expect(source).not.toContain('Routes');
    expect(source).not.toContain('collectSlashCommandsData');
    expect(source).not.toContain('rest.put');
    expect(source).not.toContain('CLIENT_ID');
  });

  test('slashCommandのルーティング自体は残る(登録しないだけで実行はする)', () => {
    const source = generateMainSource([]);
    expect(source).toContain('routeSlashCommandInteraction(interaction, slashCommands)');
  });

  test('setComponentsStateはcomponentsの動的import直後・Client生成より前に呼ばれる', () => {
    const source = generateMainSource([]);
    expect(source).toContain('setComponentsState({ buttons, selectMenus, argsSplitter: config.argsSplitter });');
    const importsIdx = source.indexOf(`await import('../src/components/slashCommands')`);
    const setStateIdx = source.indexOf('setComponentsState(');
    const clientIdx = source.indexOf('new Client(');
    expect(importsIdx).toBeLessThan(setStateIdx);
    expect(setStateIdx).toBeLessThan(clientIdx);
  });

  test('setComponentsStateはorigin/dbEnabledの組み合わせによらず常に含まれる', () => {
    for (const origin of ['dev', 'build'] as const) {
      for (const dbEnabled of [true, false]) {
        const source = generateMainSource([], { origin, dbEnabled });
        expect(source).toContain('setComponentsState({ buttons, selectMenus, argsSplitter: config.argsSplitter });');
      }
    }
  });

  test('originはヘッダーコメントにのみ影響する(省略時はdev)', () => {
    expect(generateMainSource([])).toContain('AUTO-GENERATED by `disbord dev`');
    expect(generateMainSource([], { origin: 'dev' })).toContain('AUTO-GENERATED by `disbord dev`');
    expect(generateMainSource([], { origin: 'build' })).toContain('AUTO-GENERATED by `disbord build`');
  });

  test('coreOptionはbutton/selectMenuルーティングにのみ渡り、slashCommandには渡らない', () => {
    const source = generateMainSource([]);
    expect(source).toContain(
      'routeButtonInteraction(interaction, buttons, coreOption as never, { argsSplitter: config.argsSplitter });',
    );
    expect(source).toContain('routeSelectMenuInteraction(interaction, selectMenus, coreOption as never, {');
    expect(source).toContain('routeSlashCommandInteraction(interaction, slashCommands)');
    expect(source).not.toContain('routeSlashCommandInteraction(interaction, slashCommands, coreOption');
  });

  test('button/selectMenuルーティングにはargsSplitterがconfigから渡る', () => {
    const source = generateMainSource([]);
    expect(source).toContain('argsSplitter: config.argsSplitter');
  });

  test('coreClassName未指定時はCoreクラスのimport・factory呼び出しを一切含まない', () => {
    const source = generateMainSource([]);
    expect(source).not.toContain("from '../src/");
    expect(source).toContain("createCoreStore(config.coreClass.instanceLevel ?? 'guild')");
  });

  test('coreClassName指定時は実クラスをimportし、createCoreStoreへfactoryとinstanceInvalidMessageを渡す(bot側でnew Coreを書かずに済む)', () => {
    const source = generateMainSource([], { coreClassName: 'Core' });
    expect(source).toContain("import { Core } from '../src/Core';");
    expect(source).toContain(
      "createCoreStore(config.coreClass.instanceLevel ?? 'guild', () => new Core(), config.coreClass.instanceInvalidMessage)",
    );
  });

  test('coreClassName指定時のimportはClassName別名(--core-classでカスタム名にした場合)にも対応する', () => {
    const source = generateMainSource([], { coreClassName: 'GameMaster' });
    expect(source).toContain("import { GameMaster } from '../src/GameMaster';");
    expect(source).toContain('() => new GameMaster()');
  });

  test('tokenはconfig.tokenを優先し、未指定時はprocess.env.TOKENへfallbackする', () => {
    const source = generateMainSource([]);
    expect(source).toContain('config.token ?? process.env.TOKEN');
  });

  test('disbord.config.tsのsatisfies由来の狭い推論型をConfigへ広げてから使う(未定義プロパティアクセスの型エラー対策)', () => {
    const source = generateMainSource([]);
    expect(source).toContain(`import rawConfig from '../disbord.config';`);
    expect(source).toContain('type Config');
    expect(source).toContain('const config = rawConfig as Config;');
  });

  test('BotErrorはconfig.botErrorMessageでhandleBotErrorに渡される', () => {
    const source = generateMainSource([]);
    expect(source).toContain('handleBotError(error, interaction, config.botErrorMessage)');
  });

  test('dbEnabled省略時はfalse相当(DB関連コードを一切含まない)', () => {
    const source = generateMainSource([]);
    expect(source).not.toContain('createDbClient');
    expect(source).not.toContain('db/schema');
  });

  test('dbEnabled: trueはschema importとcreateDbClient呼び出し(config.db由来のTurso接続情報付き)を含む', () => {
    const source = generateMainSource([], { dbEnabled: true });
    expect(source).toContain('createDbClient');
    expect(source).toContain(`import { schema } from '../src/db/schema';`);
    expect(source).toContain(
      'createDbClient(schema, { url: config.db?.tursoDatabaseUrl, authToken: config.db?.tursoAuthToken });',
    );
  });

  test('dbEnabled: trueのcreateDbClient呼び出しはclient生成より前', () => {
    const source = generateMainSource([], { dbEnabled: true });
    expect(source.indexOf('createDbClient(schema,')).toBeLessThan(source.indexOf('new Client('));
  });

  test('dbEnabled: falseはschema importを含まない', () => {
    const source = generateMainSource([], { dbEnabled: false });
    expect(source).not.toContain('db/schema');
  });
});
