import { describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import { generateOnceMainSource, scanOnceFiles } from '../src/cli/generateOnceMain';

const FIXTURES_DIR = join(import.meta.dir, 'fixtures');

describe('scanOnceFiles', () => {
  test('src/once/直下の.tsファイル名(拡張子抜き)をソート済みで返す', () => {
    const names = scanOnceFiles(join(FIXTURES_DIR, 'once'));
    expect(names).toEqual(['cleanup', 'notice']);
  });

  test('ディレクトリが存在しない場合は空配列(src/once/未作成のbotでもbuild/generateOnceMainが落ちないように)', () => {
    const names = scanOnceFiles(join(FIXTURES_DIR, 'once-does-not-exist'));
    expect(names).toEqual([]);
  });

  test('main.tsが存在する場合はthrow(dist/main.jsと衝突するため予約済み)', () => {
    expect(() => scanOnceFiles(join(FIXTURES_DIR, 'once-reserved'))).toThrow(/main/);
  });
});

describe('generateOnceMainSource', () => {
  test('handlerを静的importし、ClientReadyの最後でclient.destroy()を呼ぶ', () => {
    const source = generateOnceMainSource('notice');
    expect(source).toContain(`import handler from '../../src/once/notice';`);
    expect(source).toContain('client.on(Events.ClientReady, async (readyClient) => {');
    expect(source).toContain('await handler(readyClient);');
    expect(source).toContain('await client.destroy();');
  });

  test('originはヘッダーコメントにのみ影響する(省略時はonce)', () => {
    expect(generateOnceMainSource('notice')).toContain('AUTO-GENERATED by `disbord once`');
    expect(generateOnceMainSource('notice', { origin: 'once' })).toContain('AUTO-GENERATED by `disbord once`');
    expect(generateOnceMainSource('notice', { origin: 'build' })).toContain('AUTO-GENERATED by `disbord build`');
  });

  test('tokenはconfig.tokenを優先し、未指定時はprocess.env.TOKENへfallbackする', () => {
    const source = generateOnceMainSource('notice');
    expect(source).toContain('config.token ?? process.env.TOKEN');
  });

  test('slashCommand/componentsのルーティングは一切含まない(単発実行のためinteractionを扱わない)', () => {
    const source = generateOnceMainSource('notice');
    expect(source).not.toContain('InteractionCreate');
    expect(source).not.toContain('routeSlashCommandInteraction');
    expect(source).not.toContain('setComponentsState');
  });

  test('dbEnabled省略時はfalse相当(DB関連コードを一切含まない)', () => {
    const source = generateOnceMainSource('notice');
    expect(source).not.toContain('createDbClient');
    expect(source).not.toContain('db/schema');
  });

  test('dbEnabled: trueは.disbord/db/schemaからのimportとcreateDbClient呼び出しを含む(.disbord/once/配下からの相対パスのため.disbord/main.tsと異なりschemaは../db/schema)', () => {
    const source = generateOnceMainSource('notice', { dbEnabled: true });
    expect(source).toContain(`import { schema } from '../db/schema';`);
    expect(source).toContain(
      'createDbClient(schema, { url: config.db?.tursoDatabaseUrl, authToken: config.db?.tursoAuthToken });',
    );
  });

  test('dbEnabled: trueのcreateDbClient呼び出しはclient生成より前', () => {
    const source = generateOnceMainSource('notice', { dbEnabled: true });
    expect(source.indexOf('createDbClient(schema,')).toBeLessThan(source.indexOf('new Client('));
  });

  test('coreClassName未指定時はCoreクラスのimport・createCoreStore呼び出しを一切含まない', () => {
    const source = generateOnceMainSource('notice');
    expect(source).not.toContain('createCoreStore');
    expect(source).not.toContain("from '../../src/Core'");
  });

  test('coreClassName指定時は実クラスをimportし、config.coreClass.enable時のみcreateCoreStoreを呼ぶ', () => {
    const source = generateOnceMainSource('notice', { coreClassName: 'Core' });
    expect(source).toContain("import { Core } from '../../src/Core';");
    expect(source).toContain('if (config.coreClass?.enable) {');
    expect(source).toContain(
      "createCoreStore(config.coreClass.instanceLevel ?? 'guild', () => new Core(), config.coreClass.instanceInvalidMessage);",
    );
  });

  test('coreClassName指定時のimportはClassName別名(--core-classでカスタム名にした場合)にも対応する', () => {
    const source = generateOnceMainSource('notice', { coreClassName: 'GameMaster' });
    expect(source).toContain("import { GameMaster } from '../../src/GameMaster';");
    expect(source).toContain('() => new GameMaster()');
  });
});
