import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { runModelType } from '../src/cli/modelType';

const DB_ENABLED_CONFIG = `import type { Config } from 'disbord';

export default {
  intents: ['Guilds', 'GuildMessages'],
  db: { enable: true },
  botErrorMessage: 'エラーが発生しました',
} satisfies Config;
`;

const DB_DISABLED_CONFIG = `import type { Config } from 'disbord';

export default {
  intents: ['Guilds', 'GuildMessages'],
  botErrorMessage: 'エラーが発生しました',
} satisfies Config;
`;

describe('runModelType', () => {
  let dir: string;

  beforeEach(() => {
    // 生成物は`import ... from 'disbord'`という裸のspecifierを含むため、動的importでの
    // node_modules解決が本物のworkspace root(このリポジトリ直下のnode_modules/disbord)まで
    // 辿り着けるよう、OS標準のtmpdirではなくリポジトリ配下にtmp dirを作る。
    dir = mkdtempSync(join(import.meta.dir, '.tmp-model-type-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  test('disbord.config.tsでdb.enableが有効になっていない場合はthrow', async () => {
    writeFileSync(join(dir, 'disbord.config.ts'), DB_DISABLED_CONFIG);
    await expect(runModelType(dir)).rejects.toThrow();
  });

  test('src/db/models/のnamespace Data型ブロックだけを再生成する(schema.ts/migrationsは触らない)', async () => {
    writeFileSync(join(dir, 'disbord.config.ts'), DB_ENABLED_CONFIG);
    mkdirSync(join(dir, 'src/db/models'), { recursive: true });
    writeFileSync(
      join(dir, 'src/db/models/Job.ts'),
      `import { Column, Model, Table } from 'disbord';\n\n@Table('jobs')\nexport class Job extends Model<Job.Data> {\n  @Column('text')\n  accessor sample!: string;\n}\n`,
    );

    await runModelType(dir);

    const content = readFileSync(join(dir, 'src/db/models/Job.ts'), 'utf-8');
    expect(content).toContain('AUTO-GENERATED by disbord');
    expect(content).toContain('export namespace Job {');
    expect(content).toContain('export type Data = { sample: string };');

    expect(() => readFileSync(join(dir, '.disbord/db/schema.ts'), 'utf-8')).toThrow();
    expect(() => readFileSync(join(dir, 'migrations/_snapshot.json'), 'utf-8')).toThrow();
  });
});
