/**
 * `.disbord/migrate.ts`（`disbord build`が生成し`dist/migrate.js`へバンドルされる実行ファイル）のソース。
 * デプロイ先ホスト上でSSH経由で`mise exec -- bun migrate.js`として実行される想定(`WorkingDirectory`基準で
 * `migrations/`を読む)で、`disbord migrate --production`（Turso必須のままthrowする汎用CLI）とは別に、
 * Turso未設定時はローカルsqlite(`prd.db`)へフォールバックする`runProductionMigration`を使う。
 */
export function generateMigrateMainSource(): string {
  return `// AUTO-GENERATED by \`disbord build\`. Do not edit — regenerated on every build.
import { runProductionMigration, type Config } from 'disbord';
import rawConfig from '../disbord.config';

async function main() {
  // satisfiesの推論型(disbord.config.ts側のexcess property check維持のため)をConfigへ広げる
  const config = rawConfig as Config;

  const applied = await runProductionMigration(config, \`\${process.cwd()}/migrations\`);
  console.log(
    applied.length > 0
      ? \`disbord: 本番DBに\${applied.length}件のmigrationを適用しました（\${applied.join(', ')}）\`
      : 'disbord: 未適用のmigrationはありませんでした',
  );
}

void main();
`;
}
