import { readdirSync } from 'node:fs';

const RESERVED_EVENT_NAME = 'interactionCreate';

/**
 * src/events/ を走査してイベント名(拡張子抜きファイル名)一覧を返す。
 * interactionCreateはcomponents層の汎用ルーティングが専有するため、そのファイルが
 * 存在する場合は設定ミスとして即座に気づけるようthrowする。
 */
export function scanEventFiles(eventsDir: string): string[] {
  const names = readdirSync(eventsDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
    .map((entry) => entry.name.slice(0, -'.ts'.length))
    .sort();

  if (names.includes(RESERVED_EVENT_NAME)) {
    throw new Error(
      `disbord: src/events/${RESERVED_EVENT_NAME}.ts は予約済みです。interactionCreateはdisbordのcomponents層が内部で処理するため、events配下に置かないでください。`,
    );
  }

  return names;
}

function handlerIdentifier(eventName: string): string {
  return `${eventName}Handler`;
}

export type GenerateMainSourceOptions = {
  /**
   * true(dev): 起動のたびにslashCommandをグローバルREST登録する(開発時の利便性優先)。
   * false(build): 登録しない(disbord.md「ビルド」節の設計。必要ならdisbord commands pushを別途手動実行する)。
   */
  registerCommands?: boolean;
};

/**
 * .disbord/main.ts のTSソース全文を組み立てる。
 * イベントは静的importで書き出す(bundleでの解決を優先するため)。
 * buttons/selectMenus/slashCommandsは生成時点ではなく実行時に動的importする。
 * coreClass/token/clientIdの有効・無効はdisbord.config.tsの中身によって変わるが、
 * それはこのテンプレートが実行時にconfigを読んで分岐するため、
 * ここではeventNames以外の入力を必要としない(config.ts自体の変更はbun --watchが
 * 静的importのグラフ変化として自動検知し再起動する)。
 */
export function generateMainSource(eventNames: string[], options: GenerateMainSourceOptions = {}): string {
  const registerCommands = options.registerCommands ?? true;

  const eventImports = eventNames
    .map((name) => `import ${handlerIdentifier(name)} from '../src/events/${name}';`)
    .join('\n');
  const eventBindings = eventNames.map((name) => `  client.on('${name}', ${handlerIdentifier(name)});`).join('\n');

  const discordImports = registerCommands
    ? `import { Client, Events, REST, Routes } from 'discord.js';`
    : `import { Client, Events } from 'discord.js';`;
  const disbordImports = [
    'createCoreStore',
    'handleBotError',
    'routeButtonInteraction',
    'routeSelectMenuInteraction',
    'routeSlashCommandInteraction',
    ...(registerCommands ? ['collectSlashCommandsData'] : []),
  ];
  const loginBlock = registerCommands
    ? `  const TOKEN = process.env[config.token ?? 'TOKEN'];
  const CLIENT_ID = process.env[config.clientId ?? 'CLIENT_ID'];

  const rest = new REST().setToken(TOKEN!);
  await rest.put(Routes.applicationCommands(CLIENT_ID!), {
    body: collectSlashCommandsData(slashCommands),
  });

  await client.login(TOKEN);`
    : `  const TOKEN = process.env[config.token ?? 'TOKEN'];

  await client.login(TOKEN);`;

  return `// AUTO-GENERATED by \`disbord ${registerCommands ? 'dev' : 'build'}\`. Do not edit — regenerated on every restart.
${discordImports}
import {
  ${disbordImports.join(',\n  ')},
} from 'disbord';
import config from '../disbord.config';
${eventImports}

async function main() {
  const buttons = (await import('../src/components/buttons')).default;
  const selectMenus = (await import('../src/components/selectMenus')).default;
  const slashCommands = (await import('../src/components/slashCommands')).default;

  const client = new Client({ intents: config.intents });

  const coreStore = config.coreClass?.enable
    ? createCoreStore(config.coreClass.instanceLevel ?? 'guild')
    : undefined;
  const coreOption = coreStore ? { store: coreStore, nullMessage: config.coreClass!.nullMessage } : undefined;

  client.on(Events.InteractionCreate, async (interaction) => {
    if (!interaction.isRepliable()) return;
    try {
      if (interaction.isChatInputCommand()) {
        await routeSlashCommandInteraction(interaction, slashCommands);
      } else if (interaction.isButton()) {
        await routeButtonInteraction(interaction, buttons, coreOption as never);
      } else if (interaction.isStringSelectMenu()) {
        await routeSelectMenuInteraction(interaction, selectMenus, coreOption as never);
      }
    } catch (error) {
      await handleBotError(error, interaction, config.botErrorMessage);
    }
  });

${eventBindings}

${loginBlock}
}

void main();
`;
}
