import { readdirSync } from 'node:fs';

const RESERVED_EVENT_NAME = 'interactionCreate';

export function scanEventFiles(eventsDir: string): string[] {
  const names = readdirSync(eventsDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
    .map((entry) => entry.name.slice(0, -'.ts'.length))
    .sort();

  if (names.includes(RESERVED_EVENT_NAME)) {
    throw new Error(
      `disbord: src/events/${RESERVED_EVENT_NAME}.ts は予約済みです。interactionCreateはdisbordのcomponents層が内部で処理するため、events配下に置かないでください。`,
    );
  }

  return names;
}

function handlerIdentifier(eventName: string): string {
  return `${eventName}Handler`;
}

function eventBindingTarget(eventName: string): string {
  return eventName === 'ready' ? 'Events.ClientReady' : `'${eventName}'`;
}

export type GenerateMainSourceOptions = {
  origin?: 'dev' | 'build';
  dbEnabled?: boolean;
  coreClassName?: string;
};

export function generateMainSource(eventNames: string[], options: GenerateMainSourceOptions = {}): string {
  const origin = options.origin ?? 'dev';
  const dbEnabled = options.dbEnabled ?? false;
  const coreClassName = options.coreClassName;

  const eventImports = eventNames
    .map((name) => `import ${handlerIdentifier(name)} from '../src/events/${name}';`)
    .join('\n');
  const eventBindings = eventNames
    .map((name) => `  client.on(${eventBindingTarget(name)}, ${handlerIdentifier(name)});`)
    .join('\n');

  const disbordImports = [
    'type Config',
    'createCoreStore',
    'handleBotError',
    'routeButtonInteraction',
    'routeSelectMenuInteraction',
    'routeSlashCommandInteraction',
    'setComponentsState',
    ...(dbEnabled ? ['createDbClient'] : []),
  ];
  const schemaImport = dbEnabled ? `\nimport { schema } from '../src/db/schema';` : '';
  const dbInit = dbEnabled
    ? `  createDbClient(schema, { url: config.db?.tursoDatabaseUrl, authToken: config.db?.tursoAuthToken });\n\n`
    : '';
  const coreClassImport = coreClassName ? `\nimport { ${coreClassName} } from '../src/${coreClassName}';` : '';
  const coreCreateArgs = coreClassName ? `, () => new ${coreClassName}(), config.coreClass.instanceInvalidMessage` : '';

  return `// AUTO-GENERATED by \`disbord ${origin}\`. Do not edit — regenerated on every restart.
import { Client, Events } from 'discord.js';
import {
  ${disbordImports.join(',\n  ')},
} from 'disbord';
import rawConfig from '../disbord.config';${schemaImport}${coreClassImport}
${eventImports}

async function main() {
  // satisfiesの推論型(disbord.config.ts側のexcess property check維持のため)をConfigへ広げる
  const config = rawConfig as Config;

${dbInit}  const buttons = (await import('../src/components/buttons')).default;
  const selectMenus = (await import('../src/components/selectMenus')).default;
  const slashCommands = (await import('../src/components/slashCommands')).default;
  setComponentsState({ buttons, selectMenus, argsSplitter: config.argsSplitter });

  const client = new Client({ intents: config.intents });

  const coreStore = config.coreClass?.enable
    ? createCoreStore(config.coreClass.instanceLevel ?? 'guild'${coreCreateArgs})
    : undefined;
  const coreOption = coreStore ? { store: coreStore, nullMessage: config.coreClass!.nullMessage } : undefined;

  client.on(Events.InteractionCreate, async (interaction) => {
    if (!interaction.isRepliable()) return;
    try {
      if (interaction.isChatInputCommand()) {
        await routeSlashCommandInteraction(interaction, slashCommands);
      } else if (interaction.isButton()) {
        await routeButtonInteraction(interaction, buttons, coreOption as never, { argsSplitter: config.argsSplitter });
      } else if (interaction.isStringSelectMenu()) {
        await routeSelectMenuInteraction(interaction, selectMenus, coreOption as never, {
          argsSplitter: config.argsSplitter,
        });
      }
    } catch (error) {
      await handleBotError(error, interaction, config.botErrorMessage);
    }
  });

${eventBindings}

  const TOKEN = config.token ?? process.env.TOKEN;

  await client.login(TOKEN);
}

void main();
`;
}
