import { existsSync, readdirSync } from 'node:fs';

const RESERVED_ONCE_NAME = 'main';

export function scanOnceFiles(onceDir: string): string[] {
  if (!existsSync(onceDir)) return [];
  const names = readdirSync(onceDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
    .map((entry) => entry.name.slice(0, -'.ts'.length))
    .sort();

  if (names.includes(RESERVED_ONCE_NAME)) {
    throw new Error(
      `disbord: src/once/${RESERVED_ONCE_NAME}.ts は予約済みです。${RESERVED_ONCE_NAME}はdist/${RESERVED_ONCE_NAME}.js（bot本体のエントリ）と衝突するため、once配下に置けません。`,
    );
  }

  return names;
}

export type GenerateOnceMainSourceOptions = {
  origin?: 'once' | 'build';
  dbEnabled?: boolean;
  coreClassName?: string;
  hasButtons?: boolean;
  hasSelectMenus?: boolean;
};

function buildOnceDisbordImports(
  dbEnabled: boolean,
  coreClassName: string | undefined,
  hasComponents: boolean,
): string[] {
  return [
    'type Config',
    ...(hasComponents ? ['setComponentsState'] : []),
    ...(dbEnabled ? ['createDbClient'] : []),
    ...(coreClassName ? ['createCoreStore'] : []),
  ];
}

function buildOnceComponentsStateInit(hasButtons: boolean, hasSelectMenus: boolean): string {
  if (!hasButtons && !hasSelectMenus) return '';
  const fields = [
    ...(hasButtons ? ['buttons'] : []),
    ...(hasSelectMenus ? ['selectMenus'] : []),
    'argsSplitter: config.argsSplitter',
  ].join(', ');
  return `  setComponentsState({ ${fields} });\n\n`;
}

function buildOnceExtraImports(
  dbEnabled: boolean,
  coreClassName: string | undefined,
  options: GenerateOnceMainSourceOptions,
): string {
  const hasButtons = options.hasButtons ?? false;
  const hasSelectMenus = options.hasSelectMenus ?? false;
  const buttonsImport = hasButtons ? `\nimport buttons from '../../src/components/buttons';` : '';
  const selectMenusImport = hasSelectMenus ? `\nimport selectMenus from '../../src/components/selectMenus';` : '';
  const schemaImport = dbEnabled ? `\nimport { schema } from '../../src/db/schema';` : '';
  const coreClassImport = coreClassName ? `\nimport { ${coreClassName} } from '../../src/${coreClassName}';` : '';
  return `${buttonsImport}${selectMenusImport}${schemaImport}${coreClassImport}`;
}

function buildOnceInitBlock(
  dbEnabled: boolean,
  coreClassName: string | undefined,
  hasButtons: boolean,
  hasSelectMenus: boolean,
): string {
  const dbInit = dbEnabled
    ? `  createDbClient(schema, { url: config.db?.tursoDatabaseUrl, authToken: config.db?.tursoAuthToken });\n\n`
    : '';
  const componentsStateInit = buildOnceComponentsStateInit(hasButtons, hasSelectMenus);
  const coreInit = coreClassName
    ? `  if (config.coreClass?.enable) {\n    createCoreStore(config.coreClass.instanceLevel ?? 'guild', () => new ${coreClassName}(), config.coreClass.instanceInvalidMessage);\n  }\n\n`
    : '';
  return `${dbInit}${componentsStateInit}${coreInit}`;
}

/**
 * `.disbord/once/<name>.ts`（`disbord once`/`disbord build`が生成する実実行ファイル）のソース。
 * bot本体のように常駐せず、readyイベントの最後に`client.destroy()`を呼んで1回で終了する。
 * 生成先が`.disbord/once/`（2階層深い）ため相対importの深さに注意
 * （disbord.config.ts/src/配下は`../../`、schema.tsも`src/db/`配下なので同じく`../../`）。
 *
 * interactionを扱わないため`routeButtonInteraction`等のルーティングは含めないが、
 * `makeButtonRow`/`makeSelectMenuRow`はonceスクリプトが送るメッセージの組み立てに普通に使う
 * （例: 定期通知にボタンを添える）ため、buttons.ts/selectMenus.tsが存在する場合は
 * `setComponentsState`だけ呼んでおく。
 */
export function generateOnceMainSource(name: string, options: GenerateOnceMainSourceOptions = {}): string {
  const origin = options.origin ?? 'once';
  const dbEnabled = options.dbEnabled ?? false;
  const coreClassName = options.coreClassName;
  const hasButtons = options.hasButtons ?? false;
  const hasSelectMenus = options.hasSelectMenus ?? false;
  const hasComponents = hasButtons || hasSelectMenus;

  const disbordImports = buildOnceDisbordImports(dbEnabled, coreClassName, hasComponents);
  const extraImports = buildOnceExtraImports(dbEnabled, coreClassName, options);
  const initBlock = buildOnceInitBlock(dbEnabled, coreClassName, hasButtons, hasSelectMenus);

  return `// AUTO-GENERATED by \`disbord ${origin}\`. Do not edit — regenerated on every run.
import { Client, Events } from 'discord.js';
import {
  ${disbordImports.join(',\n  ')},
} from 'disbord';
import rawConfig from '../../disbord.config';
import handler from '../../src/once/${name}';${extraImports}

async function main() {
  // satisfiesの推論型(disbord.config.ts側のexcess property check維持のため)をConfigへ広げる
  const config = rawConfig as Config;

${initBlock}  const client = new Client({ intents: config.intents });

  client.on(Events.ClientReady, async (readyClient) => {
    await handler(readyClient);
    await client.destroy();
  });

  const TOKEN = config.token ?? process.env.TOKEN;

  await client.login(TOKEN);
}

void main();
`;
}
