import { existsSync, readdirSync } from 'node:fs';

const RESERVED_ONCE_NAME = 'main';

export function scanOnceFiles(onceDir: string): string[] {
  if (!existsSync(onceDir)) return [];
  const names = readdirSync(onceDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
    .map((entry) => entry.name.slice(0, -'.ts'.length))
    .sort();

  if (names.includes(RESERVED_ONCE_NAME)) {
    throw new Error(
      `disbord: src/once/${RESERVED_ONCE_NAME}.ts は予約済みです。${RESERVED_ONCE_NAME}はdist/${RESERVED_ONCE_NAME}.js（bot本体のエントリ）と衝突するため、once配下に置けません。`,
    );
  }

  return names;
}

export type GenerateOnceMainSourceOptions = {
  origin?: 'once' | 'build';
  dbEnabled?: boolean;
  coreClassName?: string;
};

/**
 * `.disbord/once/<name>.ts`（`disbord once`/`disbord build`が生成する実実行ファイル）のソース。
 * `.disbord/main.ts`（generate.ts）と違い常駐しない: readyイベントの最後に`client.destroy()`を
 * 呼んで1回で終了する。生成先が`.disbord/once/`（1階層深い）ため相対importの深さが
 * `.disbord/main.ts`と異なる点に注意（disbord.config.ts/src/配下は`../../`、
 * schema.tsのみ`.disbord/db/`配下で`../`）。
 */
export function generateOnceMainSource(name: string, options: GenerateOnceMainSourceOptions = {}): string {
  const origin = options.origin ?? 'once';
  const dbEnabled = options.dbEnabled ?? false;
  const coreClassName = options.coreClassName;

  const disbordImports = [
    'type Config',
    ...(dbEnabled ? ['createDbClient'] : []),
    ...(coreClassName ? ['createCoreStore'] : []),
  ];
  const schemaImport = dbEnabled ? `\nimport { schema } from '../db/schema';` : '';
  const dbInit = dbEnabled
    ? `  createDbClient(schema, { url: config.db?.tursoDatabaseUrl, authToken: config.db?.tursoAuthToken });\n\n`
    : '';
  const coreClassImport = coreClassName ? `\nimport { ${coreClassName} } from '../../src/${coreClassName}';` : '';
  const coreInit = coreClassName
    ? `  if (config.coreClass?.enable) {\n    createCoreStore(config.coreClass.instanceLevel ?? 'guild', () => new ${coreClassName}(), config.coreClass.instanceInvalidMessage);\n  }\n\n`
    : '';

  return `// AUTO-GENERATED by \`disbord ${origin}\`. Do not edit — regenerated on every run.
import { Client, Events } from 'discord.js';
import {
  ${disbordImports.join(',\n  ')},
} from 'disbord';
import rawConfig from '../../disbord.config';
import handler from '../../src/once/${name}';${schemaImport}${coreClassImport}

async function main() {
  // satisfiesの推論型(disbord.config.ts側のexcess property check維持のため)をConfigへ広げる
  const config = rawConfig as Config;

${dbInit}${coreInit}  const client = new Client({ intents: config.intents });

  client.on(Events.ClientReady, async (readyClient) => {
    await handler(readyClient);
    await client.destroy();
  });

  const TOKEN = config.token ?? process.env.TOKEN;

  await client.login(TOKEN);
}

void main();
`;
}
