import { createClient } from '@libsql/client';
import { generateSQLiteDrizzleJson, generateSQLiteMigration } from 'drizzle-kit/api';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildSchema } from '../db/buildSchema';
import { applyPendingMigrations } from '../db/migrationRunner';
import { readBotConfig } from './readBotConfig';
import { scanModelFiles, type ScannedModel } from './scanModelFiles';

const LOCAL_DB_PATH = 'file:.disbord/dev.db';

function timestampId(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

function generateSchemaSource(models: ScannedModel[]): string {
  const imports = models.map((m) => `import { ${m.exportName} } from './models/${m.fileName}';`).join('\n');
  const modelNames = models.map((m) => m.exportName).join(', ');
  return `// AUTO-GENERATED by \`disbord migrate\`. Do not edit — regenerated on every \`disbord migrate\` run.
import { buildSchema } from 'disbord';
${imports}

export const schema = buildSchema([${modelNames}]);
`;
}

async function runDevMigrate(cwd: string): Promise<void> {
  const modelsDir = join(cwd, 'src/db/models');
  const migrationsDir = join(cwd, 'migrations');
  const snapshotPath = join(migrationsDir, '_snapshot.json');

  const models = await scanModelFiles(modelsDir);
  writeFileSync(join(cwd, 'src/db/schema.ts'), generateSchemaSource(models));

  const schema = buildSchema(models.map((m) => m.modelClass));
  const cur = await generateSQLiteDrizzleJson(schema);

  mkdirSync(migrationsDir, { recursive: true });
  const prev = existsSync(snapshotPath)
    ? JSON.parse(readFileSync(snapshotPath, 'utf-8'))
    : await generateSQLiteDrizzleJson({});
  const statements = await generateSQLiteMigration(prev, cur);

  if (statements.length > 0) {
    const fileName = `${timestampId()}.sql`;
    writeFileSync(join(migrationsDir, fileName), statements.join('\n--> statement-breakpoint\n'));
    writeFileSync(snapshotPath, JSON.stringify(cur, null, 2));
    console.log(`disbord: migrations/${fileName} を生成しました`);
  } else {
    console.log('disbord: スキーマに変更はありません');
  }

  mkdirSync(join(cwd, '.disbord'), { recursive: true });
  const client = createClient({ url: LOCAL_DB_PATH });
  const applied = await applyPendingMigrations(client, migrationsDir);
  console.log(
    applied.length > 0
      ? `disbord: ローカルDBに${applied.length}件のmigrationを適用しました（${applied.join(', ')}）`
      : 'disbord: 未適用のmigrationはありませんでした',
  );
}

async function runProductionMigrate(cwd: string): Promise<void> {
  const migrationsDir = join(cwd, 'migrations');
  const url = process.env.TURSO_DATABASE_URL;
  if (!url) {
    throw new Error('disbord: TURSO_DATABASE_URLが設定されていません（env/.env.productionを確認してください）');
  }
  const client = createClient({ url, authToken: process.env.TURSO_AUTH_TOKEN });
  const applied = await applyPendingMigrations(client, migrationsDir);
  console.log(
    applied.length > 0
      ? `disbord: 本番DBに${applied.length}件のmigrationを適用しました（${applied.join(', ')}）`
      : 'disbord: 未適用のmigrationはありませんでした',
  );
}

async function main() {
  const production = process.argv.includes('--production');
  const cwd = process.cwd();

  const config = await readBotConfig(cwd);
  if (!config.db?.enable) {
    throw new Error('disbord: disbord.config.tsでdb.enableが有効になっていません');
  }

  if (production) {
    await runProductionMigrate(cwd);
  } else {
    await runDevMigrate(cwd);
  }
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
