import type { ColumnMeta, ModelMeta } from '../db/decorators';

/**
 * `disbord migrate`/`disbord generate model`がモデルファイル末尾に追記する
 * `namespace Xxx { export type Data = ... }`ブロックの区切り。TypeScriptの
 * namespace-classの宣言マージは同一ファイル内でしか成立しない（`declare module`による
 * 別ファイルからの拡張では`Job.Data`のような参照が解決できず`error TS2702`になる。実機確認済み）ため、
 * disbord.d.ts側に寄せず、各モデルファイル自身に都度書き戻す方式を取っている。
 */
export const DATA_BLOCK_MARKER =
  '// AUTO-GENERATED by `disbord migrate`. Do not edit below this line — regenerated on every `disbord migrate` run.';

function columnTsType(column: ColumnMeta): string {
  if (column.type === 'integer') {
    if (column.options.mode === 'timestamp_ms') return 'Date';
    if (column.options.mode === 'boolean') return 'boolean';
    return 'number';
  }
  if (column.type === 'real') return 'number';
  return 'string';
}

/**
 * `Model<Xxx.Data>`に渡すData型（コンストラクタに渡す生データの型）を、
 * @Column/@Relateのメタデータから機械的に組み立てる。
 * timestamp_msカラムはgetter越しにDayjsでラップされるが、Data自体はDB/コンストラクタに
 * 渡す生の`Date`のまま（`Model`本体のcreatedAt/updatedAtと同じ扱い）。
 */
export function buildDataTypeLiteral(meta: Pick<ModelMeta, 'columns' | 'relates'>): string {
  const fields = [
    ...meta.columns.map((column) => `${column.property}: ${columnTsType(column)}`),
    ...meta.relates.map((relate) => `${relate.property}: string`),
  ];
  return `{ ${fields.join('; ')} }`;
}

export function renderDataBlock(entries: { exportName: string; typeLiteral: string }[]): string {
  const namespaces = entries
    .map((entry) => `export namespace ${entry.exportName} {\n  export type Data = ${entry.typeLiteral};\n}`)
    .join('\n\n');
  return `${DATA_BLOCK_MARKER}\n${namespaces}\n`;
}

/**
 * 既存ファイルの内容からマーカー以降（前回生成分）を取り除いた上でblockを付け直す。
 * マーカーが無ければ末尾にそのまま追記する（`disbord generate model`直後の初回生成）。
 */
export function withDataBlock(source: string, block: string): string {
  const markerIndex = source.indexOf(DATA_BLOCK_MARKER);
  const head = (markerIndex === -1 ? source : source.slice(0, markerIndex)).trimEnd();
  return `${head}\n\n${block}`;
}
