import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readModelMeta, type ColumnMeta, type ModelMeta } from '../db/decorators';
import { formatGeneratedFile } from './formatGenerated';
import { scanModelFiles, type ScannedModel } from './scanModelFiles';

/**
 * `disbord migrate`/`disbord generate model`/`disbord model type`がモデルファイル末尾に
 * 追記する`namespace Xxx { export type Data = ... }`ブロックの区切り。TypeScriptの
 * namespace-classの宣言マージは同一ファイル内でしか成立しない（`declare module`による
 * 別ファイルからの拡張では`Job.Data`のような参照が解決できず`error TS2702`になる。実機確認済み）ため、
 * disbord.d.ts側に寄せず、各モデルファイル自身に都度書き戻す方式を取っている。
 */
export const DATA_BLOCK_MARKER =
  '// AUTO-GENERATED by disbord. Do not edit below this line — regenerated by `disbord generate model` / `disbord migrate` / `disbord model type`.';

/**
 * `mode: 'timestamp_ms'`は`Date | Dayjs`にする（`Date`のみではない）。読み取ったDayjs値
 * （例: `job.scheduledAt`）をそのままcreate()/update()に渡し回すのが自然な使い方のため、
 * Model側のnormalizeDayjsValuesがDayjs→Dateへ実行時に変換する前提で、型としても両方を
 * 受け付ける（`accessor xxx!: Dayjs;`と同じファイルに生成されるため、`Dayjs`の型解決は
 * 既にモデル側のimportで満たされている）。
 */
function columnTsType(column: ColumnMeta): string {
  if (column.type === 'integer') {
    if (column.options.mode === 'timestamp_ms') return 'Date | Dayjs';
    if (column.options.mode === 'boolean') return 'boolean';
    return 'number';
  }
  if (column.type === 'real') return 'number';
  return 'string';
}

/**
 * `Model<Xxx.Data>`に渡すData型（コンストラクタに渡す生データの型）を、
 * @Column/@Relateのメタデータから機械的に組み立てる。
 * timestamp_msカラムはgetter越しにDayjsでラップされるが、Data自体はDB/コンストラクタに
 * 渡す生の`Date`のまま（`Model`本体のcreatedAt/updatedAtと同じ扱い）。
 */
export function buildDataTypeLiteral(meta: Pick<ModelMeta, 'columns' | 'relates'>): string {
  const fields = [
    ...meta.columns.map((column) => `${column.property}: ${columnTsType(column)}`),
    ...meta.relates.map((relate) => `${relate.property}: string`),
  ];
  return `{ ${fields.join('; ')} }`;
}

export function renderDataBlock(entries: { exportName: string; typeLiteral: string }[]): string {
  const namespaces = entries
    .map((entry) => `export namespace ${entry.exportName} {\n  export type Data = ${entry.typeLiteral};\n}`)
    .join('\n\n');
  return `${DATA_BLOCK_MARKER}\n${namespaces}\n`;
}

/**
 * 既存ファイルの内容からマーカー以降（前回生成分）を取り除いた上でblockを付け直す。
 * マーカーが無ければ末尾にそのまま追記する（`disbord generate model`直後の初回生成）。
 */
export function withDataBlock(source: string, block: string): string {
  const markerIndex = source.indexOf(DATA_BLOCK_MARKER);
  const head = (markerIndex === -1 ? source : source.slice(0, markerIndex)).trimEnd();
  return `${head}\n\n${block}`;
}

/**
 * 各モデルファイル末尾の`namespace Xxx { export type Data = ... }`を、現在の@Column/@Relate
 * メタデータから再生成して書き戻す。TypeScriptのnamespace-classマージが同一ファイル内でしか
 * 成立しないため、disbord.d.ts側ではなくモデルファイル自身をここで書き換える。1ファイルに
 * 複数のモデルクラスがexportされているケースにも対応するため、fileNameでグルーピングしてから
 * ファイル単位でブロックを組み立てる。差分が無ければ書き込み・fmtはしない。
 */
export async function rewriteModelDataBlocks(cwd: string, modelsDir: string, models: ScannedModel[]): Promise<void> {
  const modelsByFile = new Map<string, ScannedModel[]>();
  for (const model of models) {
    const fileModels = modelsByFile.get(model.fileName) ?? [];
    fileModels.push(model);
    modelsByFile.set(model.fileName, fileModels);
  }

  for (const [fileName, fileModels] of modelsByFile) {
    const filePath = join(modelsDir, `${fileName}.ts`);
    const block = renderDataBlock(
      fileModels.map((model) => ({
        exportName: model.exportName,
        typeLiteral: buildDataTypeLiteral(readModelMeta(model.modelClass)),
      })),
    );
    const source = readFileSync(filePath, 'utf-8');
    const next = withDataBlock(source, block);
    if (next !== source) {
      writeFileSync(filePath, next);
      await formatGeneratedFile(cwd, filePath);
    }
  }
}

/**
 * `src/db/models/`をスキャンし、全モデルファイルのData型ブロックだけを再生成する
 * （schema.ts再生成・migrationファイルの差分計算・DB接続は行わない）。`disbord model type`
 * （型だけを素早く同期したい場面向けのCLI）と`disbord migrate`の両方から使う。
 */
export async function regenerateModelDataBlocks(cwd: string): Promise<ScannedModel[]> {
  const modelsDir = join(cwd, 'src/db/models');
  const models = await scanModelFiles(modelsDir);
  await rewriteModelDataBlocks(cwd, modelsDir, models);
  return models;
}
