import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { scanModelFiles, type ScannedModel } from './scanModelFiles';

/**
 * schema.tsは`.disbord/db/schema.ts`に生成する(モデル定義から完全に導出できる生成物のため、
 * disbord.d.ts同様gitignore対象の`.disbord/`配下に置く)。モデル本体は引き続き`src/db/models/`に
 * あるため、importパスは`.disbord/db/`から見た相対パスになる。
 */
function generateSchemaSource(models: ScannedModel[]): string {
  const imports = models.map((m) => `import { ${m.exportName} } from '../../src/db/models/${m.fileName}';`).join('\n');
  const modelNames = models.map((m) => m.exportName).join(', ');
  return `// AUTO-GENERATED by \`disbord migrate\`. Do not edit — regenerated on every \`disbord migrate\` run.
import { buildSchema } from 'disbord';
${imports}

export const schema = buildSchema([${modelNames}]);
`;
}

export function writeSchemaFile(cwd: string, models: ScannedModel[]): void {
  mkdirSync(join(cwd, '.disbord/db'), { recursive: true });
  writeFileSync(join(cwd, '.disbord/db/schema.ts'), generateSchemaSource(models));
}

/**
 * `src/db/models/`から`.disbord/db/schema.ts`だけを再生成する(namespaceブロックの書き戻し・
 * migrationファイルの差分計算・DB接続は行わない)。`.disbord/`ごと削除された状態から
 * `disbord build`だけを叩いてもschema.ts起因のbundleエラーにならないよう、buildからも呼ぶ。
 */
export async function regenerateSchemaFile(cwd: string): Promise<void> {
  const models = await scanModelFiles(join(cwd, 'src/db/models'));
  writeSchemaFile(cwd, models);
}
