import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { scanModelFiles, type ScannedModel } from './scanModelFiles';

/**
 * `buildTable(Model)`の変数名はexport名の先頭だけを小文字化したもの
 * (`User` → `user`)。他ファイルから`import { user } from '@/db/schema'`のように
 * 個別のテーブルをimportして使うための名前なので、テーブル名(snake_case/複数形とは
 * 限らない)ではなくモデルのexport名から機械的に導出する。
 */
function tableVarName(exportName: string): string {
  return exportName.charAt(0).toLowerCase() + exportName.slice(1);
}

/**
 * schema.tsは`src/db/schema.ts`に生成する(モデル本体`src/db/models/`と同じくgit管理対象の
 * 通常のソースファイルとして置き、他ファイルから個々のテーブルをimportできるようにするため)。
 * `buildTable(Model)`でモデルごとにテーブルを組み立て、`buildSchema([...])`でrelations込みの
 * スキーマにまとめる二段構成にする。モデルのimportは`schema.ts`自身の置き場所に依存しない
 * `@/db/models/*`のエイリアスにする(相対パスだとscaffold.tsの`paths: { '@/*': ['./src/*'] }`
 * 前提と食い違い、schema.tsを別の場所に置き直した際に壊れやすいため)。
 */
function generateSchemaSource(models: ScannedModel[]): string {
  const imports = models.map((m) => `import { ${m.exportName} } from '@/db/models/${m.fileName}';`).join('\n');
  const tableDefs = models
    .map((m) => `export const ${tableVarName(m.exportName)} = buildTable(${m.exportName});`)
    .join('\n');
  const tableNames = models.map((m) => tableVarName(m.exportName)).join(', ');
  return `// AUTO-GENERATED by \`disbord migrate\`. Do not edit — regenerated on every \`disbord migrate\` run.
import { buildSchema, buildTable } from 'disbord';
${imports}

${tableDefs}

export const schema = buildSchema([${tableNames}]);
`;
}

export function writeSchemaFile(cwd: string, models: ScannedModel[]): void {
  writeFileSync(join(cwd, 'src/db/schema.ts'), generateSchemaSource(models));
}

/**
 * `src/db/models/`から`src/db/schema.ts`だけを再生成する(namespaceブロックの書き戻し・
 * migrationファイルの差分計算・DB接続は行わない)。`.disbord/`ごと削除された状態から
 * `disbord build`だけを叩いてもschema.ts起因のbundleエラーにならないよう、buildからも呼ぶ。
 */
export async function regenerateSchemaFile(cwd: string): Promise<void> {
  const models = await scanModelFiles(join(cwd, 'src/db/models'));
  writeSchemaFile(cwd, models);
}
