import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { readBotConfig } from './readBotConfig';

/**
 * `.disbord/drizzle.config.ts`として都度書き出すdrizzle-kit studio専用の設定。disbord.config.tsと違い
 * ユーザー編集を想定しないため、`disbord studio`実行の度に絶対パスで丸ごと再生成する(相対パスだと
 * drizzle-kitがどこ基準で解決するか実行環境に依存して不安定なため、cwd基準の絶対パスに固定する)。
 */
export function generateDrizzleStudioConfig(cwd: string): string {
  const schemaPath = join(cwd, 'src/db/schema.ts');
  const migrationsDir = join(cwd, 'migrations');
  const dbPath = join(cwd, '.disbord/db/dev.db');
  return `// AUTO-GENERATED by \`disbord studio\`. Do not edit — regenerated on every \`disbord studio\` run.
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'sqlite',
  schema: '${schemaPath}',
  out: '${migrationsDir}',
  dbCredentials: {
    url: 'file:${dbPath}',
  },
});
`;
}

/**
 * bot自身の`node_modules`から`drizzle-kit`のbinを解決する(dotenvxSpawn.tsのresolveDotenvxBinと同じ発想)。
 * `drizzle-kit`はDB_DEPENDENCIESとしてbot自身のpackage.jsonにも明示されるため、常にbot側から解決できる。
 */
function resolveDrizzleKitBin(cwd: string): string {
  let pkgJsonPath: string;
  try {
    pkgJsonPath = Bun.resolveSync('drizzle-kit/package.json', cwd);
  } catch (error) {
    throw new Error(
      'disbord: drizzle-kitが見つかりません。db.enableが有効になっているか、依存関係が正しくインストールされているか確認してください（bun install等）。',
      { cause: error },
    );
  }
  const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf-8')) as { bin?: Record<string, string> };
  const relBinPath = pkg.bin?.['drizzle-kit'];
  if (!relBinPath) {
    throw new Error('disbord: drizzle-kitのbinエントリが見つかりませんでした');
  }
  return join(dirname(pkgJsonPath), relBinPath);
}

/**
 * `.disbord/drizzle.config.ts`の書き出し〜`drizzle-kit studio`の起動までを行い、子プロセスの
 * ハンドルを返す(exitは待たない)。`disbord studio`単体実行(exitを待って終了コードを返す)と
 * `disbord dev`からの並列起動(ハンドルだけ欲しく、失敗しても`dev`自体は継続したい)の両方から使う。
 */
export function spawnStudioProcess(cwd: string): ReturnType<typeof Bun.spawn> {
  mkdirSync(join(cwd, '.disbord/db'), { recursive: true });
  const configPath = join(cwd, '.disbord/drizzle.config.ts');
  writeFileSync(configPath, generateDrizzleStudioConfig(cwd));

  return Bun.spawn(['bun', resolveDrizzleKitBin(cwd), 'studio', '--config', configPath], {
    cwd,
    stdio: ['inherit', 'inherit', 'inherit'],
  });
}

export async function runStudio(cwd: string): Promise<number> {
  const config = await readBotConfig(cwd);
  if (!config.db?.enable) {
    throw new Error('disbord: disbord.config.tsでdb.enableが有効になっていません');
  }

  const child = spawnStudioProcess(cwd);
  await child.exited;
  return child.exitCode ?? 1;
}
